### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by crimBubble** [crimBubble/ECCsplorer#6]
## Running ECCsplorer pipeline on devices with high CPU-core counts

Running the ECCsplorer pipeline using many CPU-cores might result in crashes in the mapping module, showing errors comparable to:

`Calculating mean coverage of TR_map-all.MAPPING (ProcessID <x>; MultiID <y>)
Killed`

Current solution: reducing the CPU-core count (-cpu/--max_threads option) can avoid crashes.

**Comment by hqyone** [comment]
Is this possible to make a docker image to make the installation easier. Thank you.

**Comment by crimBubble** [comment]
## Installing ECCsplorer pipeline

> Is this possible to make a docker image to make the installation easier. Thank you.

Currently it is not possible to provide a docker image and the easiest way of installation is using a conda environment with mamba for a faster solving of the environment.

Try the following steps:
1. install [anaconda3 or miniconda3](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html)
2. install [mamba](https://github.com/mamba-org/mamba) using `conda install -c conda-forge mamba`
3. download ECCsplorer and create the environment using:
`git clone https://github.com/crimBubble/ECCsplorer`
`cd ECCsplorer`
`mamba env create -f environment.yml`
this environment will already contain all third party tools except RepeatExplorer2
4. optional: link the ECCsplorer.py to the environment bin `/.../anaconda3/envs/eccsplorer/bin/...`
5. install RepeatExplorer2 unsing
`git clone https://bitbucket.org/petrnovak/repex_tarean.git`
`cd repex_tarean`
`conda activate eccsplorer`
`make`
`sudo dpkg --add-architecture i386`
`sudo apt-get update`
`sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386`
6. edit the "Locations of 3rd party tools (PATH)" for Trimmomatic and RepeatExploer2 in _ECCsplorer/lib/config.py_ to match your installation path
7. [test](https://github.com/crimBubble/ECCsplorer/tree/master/testdata) your installation

**Comment by hanssli** [comment]
> ## Running ECCsplorer pipeline on devices with high CPU-core counts
> Running the ECCsplorer pipeline using many CPU-cores might result in crashes in the mapping module, showing errors comparable to:
> 
> `Calculating mean coverage of TR_map-all.MAPPING (ProcessID <x>; MultiID <y>) Killed`
> 
> Current solution: reducing the CPU-core count (-cpu/--max_threads option) can avoid crashes.

Hello crimBubble,
Is this problem solved? I have run the test data sucessfully. But when I run my own data, the terminal crased in the mapping step, whatever CPU core counts I set, I always got this problem. I have tried CPU 1, 4, 6 and all of cores. What should I do now?

Thanks and best wishes,
Han

**Comment by crimBubble** [comment]
Dear @hanssli ,
thanks for using our pipeline. There is no update on this specific porblem. However, do you get an error message that you can send and provide the scale of the data your running? The amount of input data in GB and the genome size would be helpful for now to narrow down your issue.
Best,
L

**Comment by hanssli** [comment]
Dear @crimBubble ,
I have run many times, but no success except for the test run. 
I found it's stopped at the step "[mapper_coordinator] INFO: Creating index file for segmehl mapping" and then crased along with terminal closed itself. There is no other error message. I have attached the screenshot here.
![截图 2024-03-15 17-32-41](https://github.com/crimBubble/ECCsplorer/assets/160239922/256a3d4b-c32b-4025-af7b-d351bce81060)

The amount of input data is four 19+G fasta  format files; the data is a little big, I use comparative moudle. However it seems the prepared steps were completed sucessfully. The genome size I set is  '-cnt auto --genome_size 750000000'.
Are there any parameters I need to change?

Thanks and best wishes,
Han

**Comment by hanssli** [comment]
Dear @crimBubble ,
I have run many times, but no success except for the test run. 
I found it's stopped at the step "[mapper_coordinator] INFO: Creating index file for segmehl mapping" and then crased along with terminal closed itself. There is no other error message. I have attached the screenshot here.
![截图 2024-03-15 17-32-41](https://github.com/crimBubble/ECCsplorer/assets/160239922/256a3d4b-c32b-4025-af7b-d351bce81060)

The amount of input data is four 19+G fasta  format files; the data is a little big, I use comparative moudle. However it seems the prepared steps were completed sucessfully. The genome size I set is  '-cnt auto --genome_size 750000000'.
Are there any parameters I need to change?

Thanks and best wishes,
Han

**Comment by hanssli** [comment]
Dear @crimBubble ,
I have run many times, but no success except for the test run. 
I found it's stopped at the step "[mapper_coordinator] INFO: Creating index file for segmehl mapping" and then crased along with terminal closed itself. There is no other error message. I have attached the screenshot here.
![截图 2024-03-15 17-32-41](https://github.com/crimBubble/ECCsplorer/assets/160239922/256a3d4b-c32b-4025-af7b-d351bce81060)

The amount of input data is four 19+G fasta  format files; the data is a little big, I use comparative moudle. However, it seems the prepared steps were completed sucessfully. The genome size I set is  '-cnt auto --genome_size 750000000'.
Are there any parameters I need to change?

Thanks and best wishes,
Han

**Comment by hanssli** [comment]
Dear @crimBubble ,
The problem seems solved by close SWAP partition just now.  I searched internet and found someone said the SWAP may affect memory, I tried to closed it, the eccsplorer is running now. Hope it can be success this time.

**Comment by 1zhikun** [comment]
Dear @crimBubble ,
May I ask how long it will take to create this environment? I have been creating it all night without passing the "Solving Environment".

**Comment by crimBubble** [comment]
Dear @1zhikun,
which method are you using for installation? If you are using conda, please try again using mamba (see the tutorials for detailed instructions). If this doesn't help, please try a different channel priority as mentioned here #7

**Comment by cyberHydrangea** [comment]
Dear @crimBubble ,
I met an error on running test-data and test-run:


2024-08-20 23:21:13,319 - [cluster_coordinator] INFO: Summarizing clustering results.
sed: can't read /home/dty/ecc_WS/testrun/eccpipe_results/clustering_results/CLUSTER_TABLE.csv: No such file or directory
/home/dty/miniconda3/envs/eccsplorer/bin/ECCsplorer/lib/eccClusterer.py:55: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.str, delimiter='\t', skiprows=1)
Traceback (most recent call last):
  File "/home/dty/miniconda3/envs/eccsplorer/bin/eccsplorer", line 815, in <module>
    main()
  File "/home/dty/miniconda3/envs/eccsplorer/bin/eccsplorer", line 785, in main
    obj_clusterer.cluster_coordinator()
  File "/home/dty/miniconda3/envs/eccsplorer/bin/ECCsplorer/lib/eccClusterer.py", line 55, in cluster_coordinator
    dtype=np.str, delimiter='\t', skiprows=1)
  File "/home/dty/miniconda3/envs/eccsplorer/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1091, in loadtxt
    next(fh)
StopIteration
2024-08-20 23:21:13,558 - [r_shutdown] INFO: Shutting down Rserve.
2024-08-20 23:21:13,559 - [exit_err] ERROR: Sorry, something went wrong.


I tried to fix but can't find CLUSTER_TABLE.csv. May I ask what's the potential mistake I made?

**Comment by crimBubble** [comment]
Dear @cyberHydrangea,
it seems ther is an issue with the clustering which did not produce the expected results. The `CLUSTER_TABLE.csv` is an output file from the RE2 seqclust. To assist you it would be helpful if you can provide the following information:

1. Is there any output files in the directory ` /home/dty/ecc_WS/testrun/eccpipe_results/clustering_results/`?
2. With the eccsplorer env active, can you run `seqclust -h`?
3. What is the last terminal/logfile output previous to the on posted here (before: "[cluster_coordinator] INFO: Summarizing clustering results.")?

**Comment by cyberHydrangea** [comment]
Dear @crimBubble ,

1. Yes there is, but the supercluster_report.html is blank. 
<img width="1024" alt="屏幕截图 2024-08-21 143051" src="https://github.com/user-attachments/assets/5c6eb988-8c6c-4243-80d6-aaf87159d04f">

2. `seqclust -h` is runnable, and it gives:
<img width="706" alt="屏幕截图 2024-08-21 142156" src="https://github.com/user-attachments/assets/ace1ad4a-0427-4ad7-a2c9-622dfdb99eb5">
<img width="752" alt="屏幕截图 2024-08-21 142234" src="https://github.com/user-attachments/assets/aceb7c17-e3ca-4b3f-b230-38ec4c2d40a7">

3. The logs looks like cluster results:
<img width="751" alt="屏幕截图 2024-08-21 143729" src="https://github.com/user-attachments/assets/e7c71ff4-9266-40f9-b1ff-4c527a71ef21">
It goes from cluster no1 to no13 twice.

**Comment by crimBubble** [comment]
Dear @cyberHydrangea ,
Very curious. It seems RE2 works but stops clustering in the middle of the run.

>  It goes from cluster no1 to no13 twice. 
This is fine, but actually should go on for roughly two more times.

I am not quite sure what the reason for this unexpected behaviour is. RE2 is a third party tool which we did no develope and therefore I have only limited knowledge about the tool. Currently I see the following possibilities:

1. Try to run seqclust on it's own (locally) using: `seqclust --paired --prefix_length 2 --output_dir testrun/RE2_out --taxon VIRIDIPLANTAE3.0 --cpu 4 testrun/read_data/REPEATEXPLORER_READY.fa --cleanup --keep_names --options ILLUMINA`
2. Or try to run RE2 on the galaxy platform online
3. Then copy the RE2 outputs (either from local or online) in to the respective ECCsplorer folder. If there are results from RE2 present it should use those without re-running the RE2 part when re-running eccsplorer.

Also while running RE2 locally monitor your hardware resources, especially RAM and storage usage. Maybe RE2 runs out of memory or storage.

If nothing above works try to reinstall everything in a new conda environment.

btw, are you working with Nobuko? If so, feel free to also reach out via email to ludwig.mann@tu-dresden.de :)

**Comment by cyberHydrangea** [comment]
Dear @crimBubble ,
It seems seqclust can't run on its own. It gives

seqclust: error: argument sequences: can't open 'testrun/read_data/REPEATEXPLORER_READY.fa': [Errno 2] No such file or directory: 'testrun/read_data/REPEATEXPLORER_READY.fa'

It seems that RE2 is missing more than just the CLUSTER_TABLE.csv file.

btw: It comes to me that when I was installing RE2 dependencies, an error occured as "E: Unable to locate package libncurses5:i386".  I'm not sure but it seems they no longer provide libncurse5?  I used libncurses6:i386 instead. Could it be the cause?

The memory situation is very stable with no abnormalities. I will try a complete reinstallation.

I am just a beginner in bioinformatics, and I am very grateful that you are willing to take the time to help me.

**Comment by crimBubble** [comment]
Dear @cyberHydrangea ,

> seqclust: error: argument sequences: can't open 'testrun/read_data/REPEATEXPLORER_READY.fa': [Errno 2] No such file or directory: 'testrun/read_data/REPEATEXPLORER_READY.fa'

This means it just did not find the file. Make sure the path to the file named `REPEATEXPLORER_READY.fa` is correct.

> btw: It comes to me that when I was installing RE2 dependencies, an error occurred as "E: Unable to locate package libncurses5:i386". I'm not sure but it seems they no longer provide libncurse5? I used libncurses6:i386 instead. Could it be the cause?

Thanks for letting me know. I am not sure if this is the issue, as it started running but stopped during the clustering.

If it still does not work after reinstalling you might try the singularity installation of RE2. Therefore run the ECCsplorer's preparation module > find the `REPEATEXPLORER_READY.fa` file and use it as input for the RE2 singularity version > copy all outputs to `/.../your/path/to/eccpipe_results/clustering_results/` > run ECCsplorer (eccsplorer should see the existing RE2 outputs and not try to re-run the RE2).

You are welcome. We all started somewhere and needed some help at the beginning :)

**Comment by cyberHydrangea** [comment]
Dear @crimBubble ,

I managed to install libncurse5:i386, however, the error has not been resolved, and it can be reasonably ruled out that libncurse5 is the cause of the problem.

The only remaining concern is that when running `mamba env create -f environment.yml`, it gave a "pip failed" message. I'm not sure if this has affected the environment, but I have manually installed all the dependencies afterwards, so theoretically, there shouldn't be any issues.

And I tried reinstallation and replacement of files in `clustering_results`, this time it can't find another csv file. I will try to install the pipeline on a different PC next time.

I really appreciate your help in resolving these small issues. Thank you again for your help.

**Comment by crimBubble** [comment]
Dear @cyberHydrangea ,

I hope it works on another PC. Maybe using a VM with an older (20, 22) Ubuntu version could also work. Let me know if the issue is persistent.
